import {
  AlignHorizontalSpaceBetween,
  BrickWall,
  CircleDashed,
  Columns3,
  Compass,
  Fence,
  Gauge,
  Grid2x2,
  Hammer,
  House,
  LayoutGrid,
  Mountain,
  PaintRoller,
  PanelsTopLeft,
  Scissors,
  Shapes,
  Square,
  SquareCheck,
  WavesLadder,
  TrendingUp,
  Triangle,
  type LucideIcon,
} from "lucide-react";

export const CALC_ICONS: Record<string, LucideIcon> = {
  decking: LayoutGrid,
  corrugated: House,
  pitch: Triangle,
  stairs: WavesLadder,
  balustrade: Columns3,
  concrete: Square,
  framing: Hammer,
  "wall-framing": Hammer,
  flooring: Grid2x2,
  tiling: Grid2x2,
  paint: PaintRoller,
  plasterboard: PanelsTopLeft,
  fencing: Fence,
  brickwork: BrickWall,
  "site-volume": Mountain,
  "check-square": SquareCheck,
  "equal-spacing": AlignHorizontalSpaceBetween,
  triangle: Shapes,
  "mitre-angle": Compass,
  levelling: Gauge,
  slope: TrendingUp,
  "arc-setout": CircleDashed,
  "cut-list": Scissors,
};
